#JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#H2 Database configuration
spring.datasource.url=jdbc:h2:file:./data/KashPad_Backend;AUTO_RECONNECT=TRUE;MODE=MySQL;
spring.datasource.username=${DB_ADMIN_USER}
spring.datasource.password=${DB_ADMIN_PASSWORD}
spring.datasource.driverClassName=org.h2.Driver

#H2 web console configuration
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.trace=false
spring.h2.console.settings.web-allow-others=false
