#General configurations
spring.application.name=KashPad-Backend
spring.profiles.active=${PROFILE}

#TLS/SSL configuration
server.ssl.enabled=true
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:keystore/KashPad_Backend.p12
server.ssl.key-store-password=${SSL_PASSWORD}
server.ssl.protocol=TLS
server.ssl.enabled-protocols=TLSv1.3
